config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :projects, only: [:show, :index, :new, :create, :update] do
    resources :comments, only: [:create, :destroy]
    resources :user_funded_projects, only: [:create]
    resources :user_owned_projects, only: [:create]
    get      '/funds',  to: 'user_funded_projects#new'
    get      '/edit', to: 'projects#edit'
    post     '/edit', to: 'projects#update'
    post '/update', to: 'projects#update_status'
  end


  post    "/projects/new", to: 'projects#create'

  post "/username/update_user_status", path: ':username/update_user_status', to: 'users#update_user_status'

  get      '/login',    to: 'sessions#new', as: "login"
  get      '/signup',   to: 'users#new'
  get      '/users',   to: 'users#index'
  post     '/login',    to: 'sessions#create'
  delete   '/logout',   to: 'sessions#destroy'
  post     '/signup',   to: 'users#create'
  get      '/username/edit', path: ':username/edit', to: 'users#edit'
  get      '/username', path: ':username',  to: 'users#show'
  patch    '/username/update', path: ':username', to: 'users#update'
  get      '/username/update_password', path: ':username/update_password', to: "users#update_password"

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :first_name, :last_name, :username, :email, :password, :phone, presence: true
  validates :email, :username, uniqueness: true

  has_many :user_funded_projects
  has_many :funded_projects, through: :user_funded_projects, source: :project

  has_many :user_roles
  has_many :roles, through: :user_roles

  has_many :user_owned_projects
  has_many :owned_projects, through: :user_owned_projects, source: :project

  before_validation :generate_slug
  # before_update :generate_slug

  def registered_user?
    roles.exists?(name: "registered_user")
  end

  def project_funder?
    roles.exists?(name: "project_funder")
  end

  def project_owner?
    roles.exists?(name: "project_owner")
  end

  def admin_user?
    roles.exists?(name: "admin_user")
  end

  def deactivated_user?
    roles.exists?(name: "deactivated_user")
  end

  def my_total_amount_funded(project)
    user_funded_projects.where(project_id: project.id).sum(:amount)
  end

private

  def generate_slug
    self.slug = username.parameterize
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.paginate(:page => params[:page], :per_page => 70)
    @user_roles = UserRole.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      @user.roles << Role.find_or_create_by(name: "registered_user")
      flash[:notice] = "Logged in as #{@user.first_name}"
      redirect_to root_path
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def show
    @registered_user = current_user
  end

  def edit
    @user = User.find_by_slug(params[:slug])
  end

  def update
    @user = current_user
    if params[:commit] == "Update Password"
      change_password
    elsif params[:update] == "admin"
      update_admin
    else
      update_user
    end
  end

  def update_password
    unless @user.token.nil?
      TwilioService.new(@user).send_message
    else
      flash[:danger] = "I'm sorry, I can't let you do that"
      redirect_to "/#{@user.slug}"
    end
  end

  def update_user_status
      if params[:update_user_status] == "deactivated"
        user = User.find_by_slug(params[:username])
        user.roles << Role.find_or_create_by(name: "deactivated_user")
        user.roles.delete(Role.find_by(name: "registered_user"))
        redirect_to users_path
      else
        user = User.find_by_slug(params[:username])
        user.roles << Role.find_or_create_by(name: "registered_user")
        user.roles.delete(Role.find_by(name: "deactivated_user"))
        redirect_to users_path
    end
  end

  private


  def update_admin
    if params[:revoke] == "admin"
      user_to_update = User.find_by_slug(params[:username])
      user_to_update.roles.delete(Role.find_by(name: "admin_user"))
      redirect_to users_path
    else
      user_to_update = User.find_by_slug(params[:username])
      user_to_update.roles << Role.find_or_create_by(name: "admin_user")
      redirect_to users_path
    end
  end

  def update_user
    @user.update_attributes(user_params)
    if @user.save
      flash[:notice] = "Account info updated"
      redirect_to "/#{@user.slug}"
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def change_password
    if @user && @user.authenticate(params[:user][:password])
      check_token
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      redirect_to "/#{@user.slug}/update_password"
    end
  end

  def check_token
    if params[:token] == @user.token
      @user.update_attribute(:password, params[:new_password])
      redirect_to "/#{@user.slug}"
    else
      flash[:danger] = "Invalid Token password unchanged"
      redirect_to "/#{@user.slug}/update_password"
    end
  end

  def user_params
    params.required(:user)
                    .permit(:username,
                            :first_name,
                            :last_name,
                            :email,
                            :phone,
                            :password,
                            :password_confirmation,
                            :avatar_url,
                            :slug
                            )
  end
end

app/views/users/edit.html.erb
<div class="container">
  <div class="card form-card">
    <div class="card-content">
      <span class="card-title black-text">Edit Your Account</span>
      <div class="form">
        <%= form_for @user, url: username_path do |f| %>
          <%= f.label :first_name %>
          <%= f.text_field :first_name %>
          <%= f.label :last_name %>
          <%= f.text_field :last_name %>
          <%= f.label :avatar_url, "Profile photo url" %>
          <%= f.text_field :avatar_url %>
          <%= f.label :email %>
          <%= f.text_field :email %>
          <%= f.label :phone %>
          <%= f.text_field :phone %>
          <%= f.label :username %>
          <%= f.text_field :username %>
          <%= f.label :password %>
          <%= f.password_field :password %>
          <%= f.submit "Update Account", class: "btn btn-color"  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="card table-card">
    <h4 class="center black-text card-title">Users Info</h4>
    <table class="user-info">
      <thead>
        <tr>
          <td>Number of Users</td>
          <td>Registered Users</td>
          <td>Project Owners</td>
          <td>Project Funders</td>
          <td>Admins</td>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @users.count %></td>
          <td class="num-regs"><%= @user_roles.num_of_registered_users %></td>
          <td><%= @user_roles.num_of_project_owners %></td>
          <td><%= @user_roles.num_of_project_funders %></td>
          <td class="num-admins"><%= @user_roles.num_of_admins %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="card table-card">
    <table class="users-table striped">
      <h4 class= "card-title black-text center">Users</h4>
      <thead>
        <tr>
          <th></th>
          <th>Username</th>
          <th>Roles</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td class="avatar"><img src="<%= user.avatar_url %>" class="circle index-avatar"></td>
            <td><%= user.username %></td>
            <td>
              <ul>
                <% user.roles.each do |role| %>
                  <li><%= format_roles(role.name) %></li>
                <% end %>
              </ul>
            </td>
            <% if user.registered_user? %>
            <td><%= button_to "Deactivate", username_update_user_status_path(user.slug, {update_user_status: "deactivated"}), class: "btn btn-color" %></td>
            <% else %>
            <td><%= button_to "Activate", username_update_user_status_path(user.slug, {update_user_status: "activate"}), class: "btn btn-color" %></td>
            <% end %>
            <% unless user.admin_user? %>
              <td><%= button_to "Make Admin", username_update_path(user.slug, {update: "admin"}), class: "btn btn-color", method: :patch %></td>
            <% else %>
              <td> <%= button_to "Revoke Admin", username_update_path(user.slug, {update: "admin", revoke: "admin"}), method: :patch, class: 'btn btn-color' %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <ul class="paginate">
    <li class="active"><%= will_paginate @users %></li>
  </ul>
</div>

app/views/users/new.html.erb
<div class="container">

  <div class="card form-card">
    <div class="card-content">
      <span class="card-title black-text">Create Your Account</span>
      <div class="form">
        <%= form_for @user, url: signup_path do |f| %>
          <%= f.label :first_name %>
          <%= f.text_field :first_name %>
          <%= f.label :last_name %>
          <%= f.text_field :last_name %>
          <%= f.label :avatar_url, "Profile photo url" %>
          <%= f.text_field :avatar_url %>
          <%= f.label :email %>
          <%= f.text_field :email %>
          <%= f.label :phone %>
          <%= f.text_field :phone %>
          <%= f.label :username %>
          <%= f.text_field :username %>
          <%= f.label :password %>
          <%= f.password_field :password %>
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation %>
          <%= f.submit "Create Account", class: "btn btn-color"  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="card hoverable margin">
      <div class="card-image left">
        <%= image_tag @registered_user.avatar_url, class: "image-size" %>
      </div>
      <div class="card-content">
        <span class="card-title"><%= @registered_user.first_name %> <%= @registered_user.last_name %></span>
        <ul>
          <li><%= @registered_user.email %></li>
          <li><%= @registered_user.username %></li>
        </ul>
      </div>

    </div>
  </div>
  <%= link_to "Edit", username_edit_path(slug: @registered_user.slug), class: "btn btn-color right" %>
  <%= link_to "Update Password", username_update_password_path(@registered_user.slug), class: "btn btn-color" %>
  <% if project_funder? %>
  <div class="card table-card">
  <table class="bordered highlight">
    <h4 class="center card-title black-text">Projects I've Funded</h4>
    <thead>
      <tr>
        <th class="center">Project Name</th>
        <th class="center">Remaining Time</th>
        <th class="center">Total Amount Funded</th>
        <th class="center">Total Amount Needed</th>
        <th class="center">Amount I've Funded</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <% @registered_user.funded_projects.each do |project| %>
        <td class="center"><a href="/projects/<%= project.slug %>"> <%= project.name %></a></td>
        <td class="center"><%= format_date(project.time) %></td>
        <td class="center"><%= number_to_currency(project.total_funds, precision: 2) %></td>
        <td class="center"><%= number_to_currency(project.total, precision: 2) %></td>
        <td class="center"><%= number_to_currency(@registered_user.my_total_amount_funded(project), precision: 2) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>
</div>
</div>

<br>
<br>
  <% if project_owner? %>
<div class="container">
  <div class="card table-card">
    <h4 class="card-title black-text center">Projects I Own</h4>
    <table class="owned-projects bordered highlight" id="owned-table">
      <thead>
        <tr>
          <th class="center">Project Name</th>
          <th class="center">Remaining Time</th>
          <th class="center">Total Amount Funded</th>
          <th class="center">Total Amount Needed</th>
          <th class="center"></th>
          <th class="center"></th>
        </tr>
      </thead>
      <tbody>
        <% @registered_user.owned_projects.each do |project| %>
        <tr>
          <td class="center"><a href="/projects/<%= project.slug %>"><%= project.name %></a></td>
          <td class="center"><%= format_date(project.time)%></td>
          <td class="center"><%= number_to_currency(project.total_funds, precision: 2) %></td>
          <td class="center"><%= number_to_currency(project.total, precision: 2) %></td>
          <td class="center"></td>
          <% if project.active? || project.funded? %>
          <td class="center"><%= link_to "Edit", project_edit_path(project.slug), class: "btn btn-color", id:"project-edit" %></td>
          <td class="center"><%= button_to "Disable", project_update_path(project, {status: "disable"}), controller: :projects, method: :update_status, class: "btn btn-color" %></td>
          <% elsif project.disabled? %>
          <td class="center"><%= button_to "Activate", project_update_path(project, {status: "active"}), controller: :projects, method: :update_status, class: "btn btn-color" %></td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
  </div>
</div>

app/views/users/update_password.html.erb
<div class="container">
  <div class="card form-card">
    <div class="card-content">
      <span class="card-title black-text">Change your password</span>
      <div class="form">
        <%= form_for @user, url: username_path do |f| %>
          <%= f.label :current_password %>
          <%= f.password_field :password %>
          <%= f.label :new_password %>
          <input id="password" type="password" name="new_password">
          <%= f.label :token %>
          <input type="text" name="token" value="">
          <%= f.submit "Update Password", class: "btn btn-color" %>
        <% end %>
      </div>
    </div>
  </div>
</div>