config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :projects, only: [:show, :index, :new, :create, :update] do
    resources :comments, only: [:create, :destroy]
    resources :user_funded_projects, only: [:create]
    resources :user_owned_projects, only: [:create]
    get      '/funds',  to: 'user_funded_projects#new'
    get      '/edit', to: 'projects#edit'
    post     '/edit', to: 'projects#update'
    post '/update', to: 'projects#update_status'
  end


  post    "/projects/new", to: 'projects#create'

  post "/username/update_user_status", path: ':username/update_user_status', to: 'users#update_user_status'

  get      '/login',    to: 'sessions#new', as: "login"
  get      '/signup',   to: 'users#new'
  get      '/users',   to: 'users#index'
  post     '/login',    to: 'sessions#create'
  delete   '/logout',   to: 'sessions#destroy'
  post     '/signup',   to: 'users#create'
  get      '/username/edit', path: ':username/edit', to: 'users#edit'
  get      '/username', path: ':username',  to: 'users#show'
  patch    '/username/update', path: ':username', to: 'users#update'
  get      '/username/update_password', path: ':username/update_password', to: "users#update_password"

end

app/views/shared/_footer.html.erb
<footer class="page-footer green lighten-2">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Crowdfunder</h5>
        <p class="grey-text text-lighten-4">We fund crowds.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2017 Copyright Text
    </div>
  </div>
</footer>

app/views/shared/_jumbotron.html.erb
		<div class="row jumbo-background">
			<div class="col s12 m12">
				<div class="icon-block">
					<h2 class="center orange-text">
						<i class="mdi-image-flash-on"></i>
					</h2>

					<h1 class="center" id="welcome">Welcome</h1>
					<p class="light flow-text center white-text">Help Make Shit Happen.</p>
				</div>
			</div>
		</div>

app/views/shared/_nav.html.erb
<nav>
  <div class="nav-wrapper green lighten-2 nav-shadow">
    <div class="container">
      <%= link_to "Crowdfunder", root_path, class:"brand-logo" %>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if current_user %>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
          <li><%= link_to "Profile", username_path({username: current_user.slug}) %></li>
          <li><%= link_to "Start a Project", new_project_path %></li>
          <% if admin_user?%>
            <li><%= link_to "User Index", users_path %></li>
            <% end %>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
        <li><%= link_to "Projects", projects_path %></li>
      </ul>
    </div>
  </div>
</nav>