config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :projects, only: [:show, :index, :new, :create, :update] do
    resources :comments, only: [:create, :destroy]
    resources :user_funded_projects, only: [:create]
    resources :user_owned_projects, only: [:create]
    get      '/funds',  to: 'user_funded_projects#new'
    get      '/edit', to: 'projects#edit'
    post     '/edit', to: 'projects#update'
    post '/update', to: 'projects#update_status'
  end


  post    "/projects/new", to: 'projects#create'

  post "/username/update_user_status", path: ':username/update_user_status', to: 'users#update_user_status'

  get      '/login',    to: 'sessions#new', as: "login"
  get      '/signup',   to: 'users#new'
  get      '/users',   to: 'users#index'
  post     '/login',    to: 'sessions#create'
  delete   '/logout',   to: 'sessions#destroy'
  post     '/signup',   to: 'users#create'
  get      '/username/edit', path: ':username/edit', to: 'users#edit'
  get      '/username', path: ':username',  to: 'users#show'
  patch    '/username/update', path: ':username', to: 'users#update'
  get      '/username/update_password', path: ':username/update_password', to: "users#update_password"

end

app/models/project.rb
class Project < ApplicationRecord
  has_many :comments

  validates :name, :description, :total, :time, presence: true
  validates :slug, uniqueness: true

  has_many :user_funded_projects
  has_many :funders, through: :user_funded_projects, source: :user

  has_many :user_owned_projects
  has_many :owners, through: :user_owned_projects, source: :user

  before_validation :generate_slug

  enum ({status: [:active, :disabled, :funded]})

  def generate_slug
    self.slug = name.parameterize
  end

  def total_funds
    user_funded_projects.sum(:amount)
  end

  def check_if_funded
    if total < total_funds
      funded!
    end
  end

  def self.closest_funded
    joins(:user_funded_projects)
      .group(:id)
      .select('projects.*, (projects.total - sum(user_funded_projects.amount)) AS funding_left')
      .order('funding_left asc')
      .having('(projects.total - sum(user_funded_projects.amount)) > 0')
      .limit(3)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @current_project ||= Project.find_by_slug(params[:id])
    @comment = Comment.new
  end

  def index
    @projects = Project.paginate(:page => params[:page], :per_page => 24)
  end

  def new
    @project = Project.new
  end

  def create
    @user = current_user
    @project = Project.new(project_params)
    @role = Role.find_or_create_by(name: "project_owner")
    if params[:contributor_email].empty?
      create_without_contributor
    else
      is_valid_contributor
    end
  end

  def edit
    @project = Project.find_by_slug(params[:project_id])
  end

  def update
    @user = current_user
    @project = @user.owned_projects.find(params[:id])
    @role = Role.find_or_create_by(name: "project_owner")
    if params[:contributor_email].empty?
      update_without_contributor
    else
      is_contributor_valid_update
    end
  end

  def update_status
    @user = current_user
    @project = current_user.owned_projects.find(params[:project_id])
    if params["status"] == "disable"
      @project.disabled!
      redirect_to username_path(@user.slug)
    else
      @project.active!
      redirect_to username_path(@user.slug)
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :image_url, :total, :slug)
  end

  def update_without_contributor
    if @project.update(project_params)
      flash[:notice] = "Your project has been updated."
      redirect_to project_path(@project.slug)
    else
      flash[:warning] = "Please enter valid information to update the project."
      render :edit
    end
  end

  def is_contributor_valid_update
    @contributor = User.find_by(email: params[:contributor_email])
    unless @contributor.nil?
      update_project
    else
      flash[:warning] = "The email doesn't exit in our database. Please remove the email or enter a valid email address."
      render :edit
    end
  end

  def update_project
    if @project.update(project_params)
      @contributor.roles << @role
      @project.owners << @contributor
      flash[:notice] = "Your project has been updated."
      redirect_to project_path(@project.slug)
    else
      flash[:error] = @project.errors.full_messages.to_sentence
      render :edit
    end
  end

  def create_without_contributor
    days = params[:time][:month].to_i
    @project.time = (Time.now.to_date + days)
    if @project.save
      @user.roles << @role
      @user.owned_projects << @project
      flash[:notice] = "You just created a project without a contributor!"
      redirect_to username_path(@user.username)
    else
      flash[:error] = @project.errors.full_messages.to_sentence
      render :new
    end
  end

  def is_valid_contributor
    @contributor = User.find_by(email: params[:contributor_email])
     unless @contributor.nil?
      create_with_valid_contributor
    else
      flash[:warning] = "The email doesn't exit in our database."
      render :new
    end
  end

  def create_with_valid_contributor
    days = params[:time][:month].to_i
    @project.time = (Time.now.to_date + days)
    if @project.save
      @user.roles << @role
      @user.owned_projects << @project
      @contributor.roles << @role
      @contributor.owned_projects << @project
      flash[:notice] = "A project was created with #{@contributor.first_name} as a joint owner."
      redirect_to username_path(@user.username)
    else
      flash[:error] = @project.errors.full_messages.to_sentence
      render :new
    end
  end
end

app/helpers/project_helper.rb
module ProjectHelper
  def format_date(date)
    end_date  = date.to_date
    now_date  = Time.now.to_date
    num_days  = (end_date - now_date).to_i
    hours     = date.hour
    now_hours = Time.now.hour
    num_hours = hours - now_hours
    if num_hours < 0
      num_days  = num_days - 1
      num_hours = 24 + num_hours
    end
    time_remaining = " #{num_days} days, #{num_hours} hours"
    time_remaining
  end

  def percent_funded(total, funds)
    funded = ((funds.to_f/total.to_f)*100).round(0)
    if funded < 100
      funded
    else
      100
    end
  end

  def real_percent(total, funds)
    ((funds.to_f/total.to_f)*100).round(0)
  end
end

app/views/projects/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col s1"><p></p></div>
    <div class="col s10">
      <div class="card form-card">
        <div class="card-content">
          <span class="card-title black-text">Edit this Project</span>
          <div class="login-form">
            <%= form_for @project do |f| %>
            <%= f.label "Title" %>
            <%= f.text_field :name %>
            <%= f.label "Image URL" %>
            <%= f.text_field :image_url %>
            <%= f.label "Description" %>
            <%= f.text_field :description %>
            <%= f.label "Contributor Email" %>
            <input type="text" name="contributor_email"></input>
            <%= f.submit "Update Project", class: "btn btn-color", method: :update %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="row project-jumbo">
  <div class="col s12 m12">
    <div class="icon-block">
      <h2 class="center orange-text">
        <i class=""></i>
      </h2>
      <h1 class="center has-single-shadow">Projects</h1>
      <p class="light flow-text center" id="tag-line">Browse our recent projects.</p>
    </div>
  </div>
</div>

<div class="contain">
  <div class="all-projs">
    <div class="row">
      <h5>Explore Our <span id="proj-count"><%= @projects.count %></span> Projects</h5>
      <% @projects.each do |project| %>
      <div class="col s3">
        <div class="card project-index">
          <div class="card-image">
            <img src="<%= project.image_url %>" class="proj-index-img">
            <span class="card-title"><%= project.name %></span>
          </div>
          <div class="card-content">
            <p> <%= project.description %> </p>
            <hb></hb>
            <div class="status-bar progress grey lighten-2">
              <div class="status-color determinate green lighten-2" style="width:<%= percent_funded(project.total, project.total_funds) %>%">
                <p id="status-size"></p>
              </div>
            </div>
          </div>
          <div class="card-action">
            <a href="/projects/<%= project.slug %>"> <%= project.name %></a>
            <% if project.check_if_funded %>
              <div id="welcome">Funded!</div>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <div class="row">
      <ul class="paginate">
        <li class="active"><%= will_paginate @projects %></li>
      </ul>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="row">
    <div class="col s1"><p></p></div>
    <div class="col s10">
      <div class="card form-card">
        <div class="card-content">
          <span class="card-title black-text">Start A Project</span>
          <div class="login-form">
            <%= form_for :project do |f| %>
            <%= f.label "Title" %>
            <%= f.text_field :name %>
            <%= f.label "Image URL" %>
            <%= f.text_field :image_url, placeholder: "www.image.com/your_image" %>
            <%= f.label "Description" %>
            <%= f.text_field :description %>
            <%= f.label "Total Time" %>
            <select class="browser-default" name= "time[month]">
              <option value="7">1 Week</option>
              <option value="31">1 Month</option>
              <option value="90">3 Months</option>
            </select>>
            <%= f.label "Amount to Raise" %>
            <%= f.text_field :total %>
            <%= f.label "Contributor Email" %>
            <input type="text" name="contributor_email"></input>
            <%= f.submit "Create Project", class: "btn btn-color" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="row project-jumbo">
  <div class="col s12 m12">
    <div class="icon-block">
      <h2 class="center proj-name">
        <%= @current_project.name %>
      </h2>
      <ul>
        <% @current_project.owners.each do |owner| %>
        <li class="center orange-text"><%= owner.username %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="card col s5">
      <div class="card-image">
        <%= image_tag @current_project.image_url %>
      </div>
    </div>
    <div class="col s1"><p></p>
    </div>
    <div class="card col s6 status-card">
      <div class="status-bar progress grey lighten-2">
        <div class="status-color determinate" style="width:<%= percent_funded(@current_project.total, @current_project.total_funds) %>%">
          <p id="status-size"></p>
        </div>
      </div>

      <div class="row">
        <% if @current_project.check_if_funded %>
        <div id="welcome" class="center">Funded!</div>
        <% end %>
        <div class="col s1 card" id="total-card">
          <h6 class="center" id="proj-total">Total Needed: <%= number_to_currency(@current_project.total, precision: 2) %><h6>
          </div>
          <div class="col s1 card" id="date-card">
            <h6 class="center"><%= format_date(@current_project.time) %> time remaining to fund!</h6>
          </div>
          <div class="card col s1" id="percent-card">
            <p class="center"><%=real_percent(@current_project.total, @current_project.total_funds) %>%</p>
          </div>
        </div>
        <div class="row">
          <div class="col s1 class card" id="total-funded">
            <h6 class="center">Total Funded:<%= number_to_currency(@current_project.total_funds, precision: 2) %></h6>
          </div>
          <% if current_user %>
          <div class="col s1 class card" id="my-funded">
            <h6 class="center">I have Funded:<%= number_to_currency(current_user.my_total_amount_funded(@current_project), precision: 2) %>
            </h6></div> <% end %>
          </div>
        </div>
      </div>
      <div class="card-action">
        <% if current_user && @current_project.active? %>
        <%= link_to "Fund", project_funds_path(@current_project), class: "btn right btn-color" %>
        <% elsif current_user && @current_project.disabled? %>
        <a class="btn btn-color disabled right">Disabled</a>
        <% else %>
        <%= link_to "Register/Sign in to fund", login_path, class: "btn right btn-color" %>

        <% end %>
      </div>

      <div class="row">
        <div class="col s12">
          <div class="card proj-card">
            <div class="card-content green-text">
              <p>Description<p>
                <h5 id="proj-description"><%= @current_project.description %></h5>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col s12">
            <div class="card proj-card">
              <div class="card-content">
                <h6>Comments</h6>
                <% if current_user %>
                <%= render partial: 'comments/new' %>
                <% end %>
                <% @current_project.comments.each do |comment| %>
                <div class="row">
                  <div class="col s8 comment-thing">
                    <div class="card">
                      <div class="card-content">
                        <p class="black-text"><%= comment.content %></p>
                        <p class="right author" ><%= comment.author %></p>
                      </div>
                    </div>
                    <% if admin_user? %>
                    <%= link_to "Delete Comment", project_comment_path(@current_project, comment), class: "btn btn-delete right", method: :delete %>
                    <% end %>
                  </div>
                </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>